# Generated by Django 3.0 on 2022-12-13 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7f7562f201f0>/', verbose_name='Картинки')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place', verbose_name='Место')),
            ],
        ),
    ]
