# Generated by Django 3.0 on 2022-12-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x7f7ae1a2c1f0>/', verbose_name='Картинки'),
        ),
    ]
