# Generated by Django 3.0 on 2022-12-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20221213_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_title',
        ),
    ]
